-- Sakura — schema aligned with src/lib/supabase.ts, creator.ts, comments.ts,
-- cloud-sync.ts, novel.ts, and src/app/api/comments/highlight/route.ts
-- Apply via Supabase SQL editor or: supabase db push (CLI)

-- Extensions (gen_random_uuid)
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============ Manga: favorites & history ============
CREATE TABLE IF NOT EXISTS public.favorites (
    wallet_address text NOT NULL,
    manga_id text NOT NULL,
    title text NOT NULL,
    cover_url text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (wallet_address, manga_id)
);

CREATE TABLE IF NOT EXISTS public.reading_history (
    wallet_address text NOT NULL,
    manga_id text NOT NULL,
    chapter_id text NOT NULL,
    last_page integer NOT NULL DEFAULT 0,
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (wallet_address, manga_id)
);

-- ============ Profiles & comments ============
CREATE TABLE IF NOT EXISTS public.user_profiles (
    wallet_address text PRIMARY KEY,
    display_name text,
    bio text,
    avatar_seed text NOT NULL DEFAULT '',
    has_pass boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.chapter_comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_address text NOT NULL,
    manga_id text NOT NULL,
    chapter_id text NOT NULL,
    content text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    edited boolean NOT NULL DEFAULT false,
    is_highlighted boolean NOT NULL DEFAULT false,
    highlight_tx text
);

CREATE INDEX IF NOT EXISTS idx_chapter_comments_manga_chapter
    ON public.chapter_comments (manga_id, chapter_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_chapter_comments_highlight_tx_unique
    ON public.chapter_comments (highlight_tx)
    WHERE highlight_tx IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.comment_reactions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id bigint NOT NULL REFERENCES public.chapter_comments (id) ON DELETE CASCADE,
    wallet_address text NOT NULL,
    emoji text NOT NULL,
    UNIQUE (comment_id, wallet_address, emoji)
);

-- ============ Creators & tips ============
CREATE TABLE IF NOT EXISTS public.creator_profiles (
    wallet_address text PRIMARY KEY,
    display_name text NOT NULL,
    bio text,
    avatar_url text,
    is_verified boolean NOT NULL DEFAULT false,
    mangadex_author_id text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_creator_profiles_author
    ON public.creator_profiles (mangadex_author_id);

CREATE TABLE IF NOT EXISTS public.tips_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tx_hash text NOT NULL,
    sender_address text NOT NULL,
    receiver_address text NOT NULL,
    amount_sol double precision NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- ============ Cloud sync (JSON blobs per wallet) ============
CREATE TABLE IF NOT EXISTS public.user_library (
    wallet_address text PRIMARY KEY,
    data jsonb NOT NULL DEFAULT '[]'::jsonb,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.user_settings (
    wallet_address text PRIMARY KEY,
    data jsonb NOT NULL DEFAULT '{}'::jsonb,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.anime_history (
    wallet_address text PRIMARY KEY,
    data jsonb NOT NULL DEFAULT '[]'::jsonb,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.manga_progress (
    wallet_address text PRIMARY KEY,
    chapter_progress jsonb NOT NULL DEFAULT '{}'::jsonb,
    read_chapters jsonb NOT NULL DEFAULT '{}'::jsonb,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.user_searches (
    wallet_address text PRIMARY KEY,
    data jsonb NOT NULL DEFAULT '{}'::jsonb,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.novel_downloads_index (
    wallet_address text PRIMARY KEY,
    data jsonb NOT NULL DEFAULT '[]'::jsonb,
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- ============ Novel bookmarks ============
CREATE TABLE IF NOT EXISTS public.novel_bookmarks (
    id text PRIMARY KEY,
    user_wallet text NOT NULL,
    novel_id text NOT NULL,
    chapter_id text NOT NULL,
    source text,
    type text NOT NULL DEFAULT 'bookmark',
    position_percent double precision,
    selected_text text,
    note text,
    color text NOT NULL DEFAULT 'yellow',
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_novel_bookmarks_user ON public.novel_bookmarks (user_wallet);

-- ============ Sakura novels ============
CREATE TABLE IF NOT EXISTS public.novels (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    creator_wallet text NOT NULL,
    title text NOT NULL DEFAULT '',
    description text NOT NULL DEFAULT '',
    cover_url text NOT NULL DEFAULT '',
    genres text[] NOT NULL DEFAULT '{}',
    status text NOT NULL DEFAULT 'ongoing',
    language text NOT NULL DEFAULT 'en',
    free_until_chapter integer NOT NULL DEFAULT 0,
    paid_from_chapter integer NOT NULL DEFAULT 1,
    price_per_chapter numeric NOT NULL DEFAULT 0,
    allow_pass boolean NOT NULL DEFAULT false,
    published boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_novels_creator ON public.novels (creator_wallet);

CREATE TABLE IF NOT EXISTS public.novel_chapters (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    novel_id uuid NOT NULL REFERENCES public.novels (id) ON DELETE CASCADE,
    chapter_number integer NOT NULL,
    title text NOT NULL DEFAULT '',
    content text NOT NULL DEFAULT '',
    word_count integer NOT NULL DEFAULT 0,
    is_free_override boolean NOT NULL DEFAULT false,
    published boolean NOT NULL DEFAULT false,
    release_time timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (novel_id, chapter_number)
);

CREATE TABLE IF NOT EXISTS public.novel_unlocks (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_wallet text NOT NULL,
    novel_id uuid NOT NULL REFERENCES public.novels (id) ON DELETE CASCADE,
    chapter_number integer NOT NULL,
    tx_signature text NOT NULL,
    amount numeric NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (user_wallet, novel_id, chapter_number)
);

CREATE TABLE IF NOT EXISTS public.novel_progress (
    user_wallet text NOT NULL,
    novel_id uuid NOT NULL REFERENCES public.novels (id) ON DELETE CASCADE,
    chapter_number integer NOT NULL,
    scroll_position double precision NOT NULL DEFAULT 0,
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_wallet, novel_id)
);

CREATE TABLE IF NOT EXISTS public.novel_milestones (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_wallet text NOT NULL,
    novel_id uuid NOT NULL REFERENCES public.novels (id) ON DELETE CASCADE,
    milestone_type text NOT NULL,
    chapter_number integer,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (user_wallet, novel_id, milestone_type, chapter_number)
);

CREATE TABLE IF NOT EXISTS public.novel_comments (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_wallet text NOT NULL,
    novel_id uuid NOT NULL REFERENCES public.novels (id) ON DELETE CASCADE,
    chapter_number integer,
    content text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_novel_comments_novel ON public.novel_comments (novel_id);
